1. Write a Python Program to find sum of array?


In [16]:
def sum(arr):
    total = 0
    for i in arr:
        total += i
    return total
print(sum([1, 2, 3, 3, 7]))


16


2. Write a Python Program to find largest element in an array?


In [3]:
array = []
size = int(input("Length of array: "))
for i in range(size):
    elements = int(input())
    array.append(elements)
    
print("provided array: {} \n and largest element in given array is: {}".format(array,max(array)))

Length of array: 5
2
3
77
986
567
provided array: [2, 3, 77, 986, 567] 
 and largest element in given array is: 986


3. Write a Python Program for array rotation?


In [4]:
import numpy as np  
array = np.arange(12).reshape(3, 4)
print(array)  
print("\nRotated array : \n", np.rot90(array))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Rotated array : 
 [[ 3  7 11]
 [ 2  6 10]
 [ 1  5  9]
 [ 0  4  8]]


In [ ]:
4. Write a Python Program to Split the array and add the first part to the end?

In [5]:
array = []
size = int(input("Length of array: "))
for i in range(size):
    elements = int(input())
    array.append(elements)
print(array)

mid = size//2

split = array[:mid]
print("splitted part is: ",split)

array = array[mid:]
print("after spliting remaining array is: ",array)

array = array+split
print("Final Array: ",array)

Length of array: 3
23
56
2
[23, 56, 2]
splitted part is:  [23]
after spliting remaining array is:  [56, 2]
Final Array:  [56, 2, 23]


In [ ]:
5. Write a Python Program to check if given array is Monotonic?

In [6]:
def isMonotonic(x):  
    return (all(x[i] <= x[i + 1] for i in range(len(x) - 1)) or all(x[i] >= x[i + 1] for i in range(len(x) - 1)))
isMonotonic([6,5,4,2,3])

False